/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/_system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_system/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get app metadata */
        get: operations["app_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dids/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve DID
         * @description This endpoint is fully compliant with the W3C DID Resolution specification. It returns a DID Resolution Result object, including metadata and the resolved DID Document, following the standard resolution process.
         *
         *     Optional resolution options may be provided as query parameters, but are not yet supported in this implementation.
         */
        get: operations["did_resolver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dids/{did}/protobuf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get DIDData protobuf
         * @description The returned data is a protobuf message compatible with the legacy prism-node implementation. The object is encoded in hexadecimal format. This endpoint is useful for testing and verifying compatibility with existing operations already anchored on the blockchain.
         */
        get: operations["did_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/indexer-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get indexer statistics */
        get: operations["indexer_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get operation details */
        get: operations["operation_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a PRISM object
         * @description Submits a PRISM object containing signed operations to the blockchain. Accepts a hex-encoded PrismObject protobuf message containing a PrismBlock with SignedPrismOperation messages and returns the transaction ID along with the computed operation IDs for tracking.
         */
        post: operations["submit_object"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/signed-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit signed operations
         * @description Submits one or more signed PRISM operations to the blockchain. Accepts an array of hex-encoded SignedPrismOperation protobuf messages and returns the transaction ID along with the computed operation IDs for tracking.
         */
        post: operations["submit_signed_operations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{tx_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transaction details */
        get: operations["transaction_details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vdr-data/{entry_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve VDR entry
         * @description Returns the raw blob data for a VDR entry, using PrismDidService::resolve_vdr. The response is application/octet-stream.
         */
        get: operations["resolve_vdr_blob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vdr-data/{entry_hash}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get VDR entry metadata
         * @description Returns metadata for a VDR entry including the latest event hash and status. This is used by VDR clients to obtain the previous event hash required for update and delete operations.
         */
        get: operations["vdr_entry_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorResponseBody: {
            message: string;
        };
        AppMeta: {
            mode: components["schemas"]["AppMetaRunMode"];
            version: string;
        };
        /** @enum {string} */
        AppMetaRunMode: "Indexer" | "Submitter" | "Standalone";
        /**
         * @description # Example
         *     ```
         *     use identus_apollo::base64::Base64UrlStrNoPad;
         *
         *     let b = b"hello world";
         *     let b64 = Base64UrlStrNoPad::from(b);
         *     assert!(b64.to_string() == "aGVsbG8gd29ybGQ");
         *     ```
         */
        Base64UrlStrNoPad: string;
        /**
         * Format: int64
         * @example 42
         */
        BlockNo: number;
        /** @example did:example:123456789abcdefghi */
        Did: string;
        DidDocument: {
            "@context": string[];
            alsoKnownAs?: components["schemas"]["Uri"][] | null;
            assertionMethod?: components["schemas"]["VerificationMethodOrRef"][] | null;
            authentication?: components["schemas"]["VerificationMethodOrRef"][] | null;
            capabilityDelegation?: components["schemas"]["VerificationMethodOrRef"][] | null;
            capabilityInvocation?: components["schemas"]["VerificationMethodOrRef"][] | null;
            id: components["schemas"]["Did"];
            keyAgreement?: components["schemas"]["VerificationMethodOrRef"][] | null;
            service?: components["schemas"]["Service"][] | null;
            verificationMethod: components["schemas"]["VerificationMethod"][];
        };
        DidDocumentMetadata: {
            canonicalId?: null | components["schemas"]["Did"];
            /** Format: date-time */
            created?: string | null;
            deactivated?: boolean | null;
            /** Format: date-time */
            updated?: string | null;
            versionId?: string | null;
        };
        DidResolutionError: {
            detail?: string | null;
            title?: string | null;
            type: components["schemas"]["DidResolutionErrorCode"];
        };
        /** @enum {string} */
        DidResolutionErrorCode: "https://www.w3.org/ns/did#INVALID_DID" | "https://www.w3.org/ns/did#INVALID_DID_DOCUMENT" | "https://www.w3.org/ns/did#NOT_FOUND" | "https://www.w3.org/ns/did#REPRESENTATION_NOT_SUPPORTED" | "https://www.w3.org/ns/did#INVALID_DID_URL" | "https://www.w3.org/ns/did#METHOD_NOT_SUPPORTED" | "https://www.w3.org/ns/did#INVALID_OPTIONS" | "https://www.w3.org/ns/did#INTERNAL_ERROR" | "https://w3id.org/security#INVALID_PUBLIC_KEY" | "https://w3id.org/security#INVALID_PUBLIC_KEY_LENGTH" | "https://w3id.org/security#INVALID_PUBLIC_KEY_TYPE" | "https://w3id.org/security#UNSUPPORTED_PUBLIC_KEY_TYPE" | "https://w3id.org/security#INVALID_VERIFICATION_METHOD_URL" | "https://w3id.org/security#INVALID_CONTROLLED_IDENTIFIER_DOCUMENT_ID" | "https://w3id.org/security#INVALID_CONTROLLED_IDENTIFIER_DOCUMENT" | "https://w3id.org/security#INVALID_VERIFICATION_METHOD" | "https://w3id.org/security#INVALID_RELATIONSHIP_FOR_VERIFICATION_METHOD";
        DidResolutionMetadata: {
            contentType?: string | null;
            error?: null | components["schemas"]["DidResolutionError"];
        };
        IndexerStats: {
            last_prism_block_number?: null | components["schemas"]["BlockNo"];
            last_prism_slot_number?: null | components["schemas"]["SlotNo"];
        };
        Jwk: {
            crv: string;
            kty: string;
            x?: null | components["schemas"]["Base64UrlStrNoPad"];
            y?: null | components["schemas"]["Base64UrlStrNoPad"];
        };
        ObjectSubmissionRequest: {
            object: components["schemas"]["PrismObjectHexStr"];
        };
        OperationDetails: {
            /** Format: int32 */
            absn: number;
            block_number: components["schemas"]["BlockNo"];
            /** Format: date-time */
            block_timestamp: string;
            did: components["schemas"]["Did"];
            operation_id: components["schemas"]["OperationId"];
            /** Format: int32 */
            osn: number;
            signed_operation_data: components["schemas"]["SignedPrismOperationHexStr"];
            slot_number: components["schemas"]["SlotNo"];
            tx_id: components["schemas"]["TxId"];
        };
        /** @example a1b2c3d4e5f6789012345678901234567890123456789012345678901234abcd */
        OperationId: string;
        OperationSummary: {
            did: components["schemas"]["Did"];
            operation_id: components["schemas"]["OperationId"];
            /** Format: int32 */
            osn: number;
            signed_operation_data: components["schemas"]["SignedPrismOperationHexStr"];
        };
        /**
         * @description A hexadecimal string representing a PrismObject protobuf message (see: https://github.com/hyperledger-identus/neoprism/blob/main/lib/did-prism/proto/prism.proto). The bytes are hex-encoded after protobuf serialization.
         * @example 22d60112d3010a086d61737465722d3012463044022036393f3602cc2c17552cf72a6af1d12dc45cdf549707e76491b06d0becbd2ece02203ff703fabf4db876059aaf1ffb7803e40f5c707695ad215fd562b2f418aaded11a7f0a7d0a7b123c0a086d61737465722d3010014a2e0a09736563703235366b31122103b20404f350d87eec98982131c176acfea520f26f8901fe08b619a56a0dd9e417123b0a0769737375652d3010024a2e0a09736563703235366b311221037ee52f2a266aa874dc83feb8fcb15ab96282f67132bc7821c08ac524955114f1
         */
        PrismObjectHexStr: string;
        ResolutionResult: {
            didDocument?: null | components["schemas"]["DidDocument"];
            didDocumentMetadata: components["schemas"]["DidDocumentMetadata"];
            didResolutionMetadata: components["schemas"]["DidResolutionMetadata"];
        };
        Service: {
            id: string;
            serviceEndpoint: components["schemas"]["ServiceEndpoint"];
            type: components["schemas"]["ServiceType"];
        };
        ServiceEndpoint: components["schemas"]["StringOrMap"] | components["schemas"]["StringOrMap"][];
        ServiceType: string | string[];
        SignedOperationSubmissionRequest: {
            signed_operations: components["schemas"]["SignedPrismOperationHexStr"][];
        };
        /**
         * @description A hexadecimal string representing a SignedPrismOperation protobuf message (see: https://github.com/hyperledger-identus/neoprism/blob/main/lib/did-prism/proto/prism.proto). The bytes are hex-encoded after protobuf serialization.
         * @example 0a086d61737465722d30124630440220442eec28ec60464acd8df155e73f88a1c7faf4549975582ff0601449525aba31022019257250071818066b377b83a8b1765df1b7dc21d9bccfc7d5da036801d3ba0e1a420a400a3e123c0a086d61737465722d3010014a2e0a09736563703235366b3112210398e61c14328a6a844eec6dc084b825ae8525f10204e9244aaf61260bd221a457
         */
        SignedPrismOperationHexStr: string;
        /**
         * Format: int64
         * @example 8086
         */
        SlotNo: number;
        StringOrMap: string | {
            [key: string]: unknown;
        };
        SubmissionResponse: {
            operation_ids: components["schemas"]["OperationId"][];
            tx_id: components["schemas"]["TxId"];
        };
        TransactionDetails: {
            /** Format: int32 */
            absn: number;
            block_number: components["schemas"]["BlockNo"];
            /** Format: date-time */
            block_timestamp: string;
            /** Format: int32 */
            operation_count: number;
            operations: components["schemas"]["OperationSummary"][];
            slot_number: components["schemas"]["SlotNo"];
            tx_id: components["schemas"]["TxId"];
        };
        /** @example 5ab0cf7e4c7cd4b63ba84a4fe299409be12ba85607cb6d1a149e80bc2eac070d */
        TxId: string;
        /** @example http://example.com */
        Uri: string;
        VdrEntryMetadataResponse: {
            entry_hash: string;
            latest_event_hash: string;
            status: string;
        };
        VerificationMethod: {
            controller: string;
            id: string;
            publicKeyJwk?: null | components["schemas"]["Jwk"];
            type: string;
        };
        VerificationMethodOrRef: components["schemas"]["VerificationMethod"] | string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example Ok */
                    "text/plain": string;
                };
            };
        };
    };
    app_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppMeta"];
                };
            };
            /** @description An unexpected error occurred while retrieving app metadata */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    did_resolver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The Decentralized Identifier (DID) to resolve.
                 * @example did:example:123456789abcdefghi
                 */
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully resolved the DID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DidDocument"];
                    "application/did": components["schemas"]["DidDocument"];
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description The provided DID is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description The DID does not exist or not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description The requested representation is not supported. */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description The DID has been deactivated. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description An unexpected error occurred during resolution. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
            /** @description A functionality is not implemented. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/did-resolution": components["schemas"]["ResolutionResult"];
                };
            };
        };
    };
    did_data: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Decentralized Identifier (DID) for which to retrieve the DIDData protobuf message. */
                did: components["schemas"]["Did"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved the DIDData protobuf message, encoded as a hexadecimal string. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The provided DID is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description The DID does not exist in the index. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred while retrieving DIDData. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description A functionality is not implemented. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    indexer_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved indexer statistics, including the latest processed slot and block numbers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerStats"];
                };
            };
            /** @description An unexpected error occurred while retrieving indexer statistics. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Indexer service is not available. */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    operation_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Operation hash (64-character hex string) */
                operation_id: components["schemas"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved operation details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationDetails"];
                };
            };
            /** @description The provided operation ID is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description The operation does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    submit_object: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectSubmissionRequest"];
            };
        };
        responses: {
            /** @description Object submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Malformed request or invalid object */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred during submission */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    submit_signed_operations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignedOperationSubmissionRequest"];
            };
        };
        responses: {
            /** @description Operations submitted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResponse"];
                };
            };
            /** @description Malformed request or invalid operations */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred during submission */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    transaction_details: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cardano transaction hash (64-character hex string) */
                tx_id: components["schemas"]["TxId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved transaction details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetails"];
                };
            };
            /** @description The provided transaction ID is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description The transaction does not exist or contains no PRISM operations */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    resolve_vdr_blob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The hex-encoded entry hash to resolve. */
                entry_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully resolved the VDR entry. Returns the blob data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description The VDR entry was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred during VDR resolution. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
    vdr_entry_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The hex-encoded entry hash. */
                entry_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved VDR entry metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VdrEntryMetadataResponse"];
                };
            };
            /** @description The provided entry hash is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description The VDR entry was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
            /** @description An unexpected error occurred. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseBody"];
                };
            };
        };
    };
}
