/**
 * @module API
 *
 * ## Type-safe Cloud Agent client
 *
 * A minimal, dependency-free client built on native `fetch` and the types
 * generated by `openapi-typescript` (see `./schema.d.ts`).
 *
 * It infers, per endpoint:
 * - the allowed URL paths for each HTTP method,
 * - required/optional path params, query params and JSON request body,
 * - the JSON response body for the success status code.
 *
 * Regenerate the underlying types from the running Cloud Agent with:
 *   curl -s http://localhost:8085/docs/docs.yaml -o prism-openapi.yaml
 *   npx openapi-typescript ./prism-openapi.yaml -o ./apps/portal/src/api/schema.d.ts
 *
 * @category API
 */
import type { paths } from './spec';

export type HttpMethod =
  | 'get'
  | 'put'
  | 'post'
  | 'delete'
  | 'patch'
  | 'head'
  | 'options';

/** Union of path strings in the spec that implement a given HTTP method. */
export type PathsWithMethod<M extends HttpMethod> = {
  [P in keyof paths]: paths[P] extends Record<M, unknown> ? P : never;
}[keyof paths];

/** The OpenAPI operation object for a `path` + `method`. */
type OperationOf<P extends keyof paths, M extends HttpMethod> =
  paths[P] extends Record<M, infer O> ? O : never;

/** `never`-ish detection: openapi-typescript emits empty objects for "no params". */
type EmptyToUndefined<T> = T extends Record<string, never>
  ? undefined
  : keyof T extends never
    ? undefined
    : T;

type PathParamsOf<O> = O extends { parameters: { path: infer T } }
  ? EmptyToUndefined<T>
  : undefined;

type QueryParamsOf<O> = O extends { parameters: { query: infer T } }
  ? EmptyToUndefined<T>
  : undefined;

type RequestBodyOf<O> = O extends {
  requestBody: { content: { 'application/json': infer B } };
}
  ? B
  : O extends { requestBody?: { content: { 'application/json': infer B } } }
    ? B | undefined
    : undefined;

type SuccessStatus = 200 | 201 | 202 | 203 | 204;
type JSONContentOf<R> = R extends { content: { 'application/json': infer B } }
  ? B
  : unknown;

/** JSON body of the (first) success response, or `unknown` if none documented. */
export type ResponseBodyOf<O> = O extends { responses: infer R }
  ? [SuccessStatus & keyof R] extends [never]
    ? unknown
    : JSONContentOf<R[SuccessStatus & keyof R]>
  : unknown;

/** Per-request arguments, with required-ness derived from the spec. */
type RequestArgs<O> = {
  headers?: Record<string, string>;
  signal?: AbortSignal;
} & (PathParamsOf<O> extends undefined
  ? { params?: undefined }
  : { params: PathParamsOf<O> }) &
  (QueryParamsOf<O> extends undefined
    ? { query?: undefined }
    : { query: QueryParamsOf<O> }) &
  (RequestBodyOf<O> extends undefined
    ? { body?: undefined }
    : undefined extends RequestBodyOf<O>
      ? { body?: RequestBodyOf<O> }
      : { body: RequestBodyOf<O> });

/** True when the request args object has at least one required key. */
type HasRequiredKeys<T> = {
  [K in keyof T]-?: Record<string, never> extends Pick<T, K> ? never : K;
}[keyof T] extends never
  ? false
  : true;

/** Makes the options argument optional unless the endpoint requires something. */
type MaybeOptionalArgs<O> =
  HasRequiredKeys<RequestArgs<O>> extends true
    ? [options: RequestArgs<O>]
    : [options?: RequestArgs<O>];

/** Discriminated result, so callers can branch on `data` vs `error`. */
export type FetchResult<O> =
  | { data: ResponseBodyOf<O>; error?: undefined; response: Response }
  | { data?: undefined; error: unknown; response: Response };

export type ClientOptions = {
  baseUrl: string;
  headers?: Record<string, string>;
  fetch?: typeof fetch;
};

type RuntimeArgs = {
  params?: Record<string, string | number | boolean>;
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
  headers?: Record<string, string>;
  signal?: AbortSignal;
};

function buildUrl(baseUrl: string, path: string, args: RuntimeArgs): string {
  let resolved = path;
  if (args.params) {
    for (const [key, value] of Object.entries(args.params)) {
      resolved = resolved.replace(
        `{${key}}`,
        encodeURIComponent(String(value)),
      );
    }
  }
  let query = '';
  if (args.query) {
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(args.query)) {
      if (value !== undefined) search.append(key, String(value));
    }
    const qs = search.toString();
    if (qs) query = `?${qs}`;
  }
  return `${baseUrl.replace(/\/$/, '')}${resolved}${query}`;
}

/**
 * Creates a type-safe client for the Cloud Agent.
 *
 * ```ts
 * const agent = createClient({ baseUrl: 'http://localhost:8085' });
 * const { data, error } = await agent.GET('/did-registrar/dids/{longFormDid}', {
 *   params: { longFormDid: 'did:prism:...' },
 * });
 * ```
 */
export function createClient(clientOptions: ClientOptions) {
  const doFetch = clientOptions.fetch ?? fetch;

  async function request<O>(
    method: HttpMethod,
    path: string,
    args: RuntimeArgs,
  ): Promise<FetchResult<O>> {
    const url = buildUrl(clientOptions.baseUrl, path, args);
    const hasBody = args.body !== undefined && args.body !== null;
    const response = await doFetch(url, {
      method: method.toUpperCase(),
      headers: {
        ...(hasBody ? { 'Content-Type': 'application/json' } : {}),
        ...clientOptions.headers,
        ...args.headers,
      },
      body: hasBody ? JSON.stringify(args.body) : undefined,
      signal: args.signal,
    });

    const contentType = response.headers.get('content-type') ?? '';
    const payload = contentType.includes('application/json')
      ? await response.json().catch(() => undefined)
      : await response.text().catch(() => undefined);

    if (response.ok) {
      return { data: payload as ResponseBodyOf<O>, response };
    }
    return { error: payload, response };
  }

  const method =
    <M extends HttpMethod>(verb: M) =>
    <P extends PathsWithMethod<M>>(
      path: P,
      ...[options]: MaybeOptionalArgs<OperationOf<P, M>>
    ): Promise<FetchResult<OperationOf<P, M>>> =>
      request<OperationOf<P, M>>(
        verb,
        path as string,
        (options ?? {}) as RuntimeArgs,
      );

  return {
    GET: method('get'),
    PUT: method('put'),
    POST: method('post'),
    DELETE: method('delete'),
    PATCH: method('patch'),
    HEAD: method('head'),
    OPTIONS: method('options'),
  };
}

export type CloudAgentClient = ReturnType<typeof createClient>;
